### ISSUE TITLE
Need you add QuicTpuConnection so much ^_^

### ISSUE THREAD

**Issue by solotop999** [lmvdz/tpu-client#2]
I am using your source code and it is very good. I'm not good at coding hope you can add QuickTpuConnection feature soon

**Comment by lmvdz** [comment]
I can try! Can you explain what that is?

**Comment by lmvdz** [comment]
I looked into it, and NodeJS did have a QUIC experimental build, but as of now there is no official support from NodeJS.

https://github.com/nodejs/node/issues/38478
