### ISSUE TITLE
How to correctly import tpu-client?

### ISSUE THREAD

**Issue by davewhiiite** [lmvdz/tpu-client#3]
Hi, I am using `tpu-client` as an imported module in my js script. The method I used to import was `pnpm install tpu-client`. No problems there.

Next, I import as follows: 
`import { TpuConnection } from 'tpu-client' ;`

set up the connection as follows:
`const rpcUrl = 'https://ssc-dao.genesysgo.net/';
const tpuConnection = TpuConnection.load(rpcUrl, { commitment: 'processed '});`

The library seems to be installed correctly, and exists in the `node_modules` directory. But when I try to use the tpuConnection to do something meaningful, it appears that meat of the lib is not available within my script:
`const txid = await tpuConnection.sendTransaction(...)`
returns error:
`tpuConnection.sendTransaction is not a function`

The same goes for any other native Connection feature. In there an example of how to correctly import and use the library? Any help greatly appreciated. Thank you.

**Comment by lmvdz** [comment]
`TpuConnection.load` returns a Promise. Try awaiting it or using `.then(tpuConnection => {})` to consume it.

https://github.com/lmvdz/tpu-client/blob/main/src/index.ts#L398

I've updated the README.md

**Comment by davewhiiite** [comment]
Solid. I also spied your github and saw how you were implementing a connection, I was doing it wrong. Thanks for the reply. I'll close the ticket. Great library, btw. Thanks!
